"""Add named foreign key constraints to Grade model

Revision ID: fddf89d1955b
Revises: 
Create Date: 2024-09-04 10:31:58.260940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddf89d1955b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quiz', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assignment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('midsem', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exam', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_grade_student', 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key('fk_grade_course', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint('fk_grade_course', type_='foreignkey')
        batch_op.drop_constraint('fk_grade_student', type_='foreignkey')
        batch_op.drop_column('exam')
        batch_op.drop_column('midsem')
        batch_op.drop_column('assignment')
        batch_op.drop_column('quiz')
        batch_op.drop_column('semester')
        batch_op.drop_column('year')
        batch_op.drop_column('student_id')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
